In [1]:
import pandas as pd
from maerkte import kmeans_cluster_maerkte, synth_maerkte, synth_maerkte_custom
from bestellungen import kmeans_cluster_bestellungen, synth_bestellungen, synth_bestellungen_custom
from bestellpositionen import synth_bestellpositionen
from resampling import resampling_hochrechnung, resampling_maerkte, resampling_bestellungen
from analyse import korrelation_maerkte, korrelation_bestellungen

df = pd.read_parquet('C:/Users/fabik/OneDrive/Projekte/a_synth_data_bachelor/data/raw/orderlines_dezember.parquet')

## Test auf Marktebene

### Marktcluster

In [ ]:
df_maerkte = df.copy()

df_maerkte = kmeans_cluster_maerkte(df_maerkte)

df_maerkte

### Marktgenerierung

In [ ]:
marktmix = {
    0: 0.1,
    1: 0.6,
    2: 0.3
}

maerkte_neu = synth_maerkte(df_maerkte, 409)

maerkte_neu

## Test auf Bestellebene

### Bestellcluster

In [ ]:
df_bestellungen = df.copy()

df_bestellungen = kmeans_cluster_bestellungen(df_bestellungen)

df_bestellungen

### Bestellgenerierung

In [ ]:
bestellmix = {
  0: {0: 0.2, 1: 0.8},
  1: {0: 0.4, 1: 0.6},
  2: {0: 0.1, 1: 0.9}
}

bestellungen_neu = synth_bestellungen(df_bestellungen, df_maerkte, maerkte_neu)

bestellungen_neu

## Test auf Bestellpositionseben

### Bestellpositionen generieren

In [ ]:
positionen_neu = synth_bestellpositionen(df,df_bestellungen, bestellungen_neu)

positionen_neu

# Test auf Resampling

In [ ]:
df_resampling = resampling_hochrechnung(df, 100)

df_resampling

In [ ]:
df_resampling_maerkte = resampling_maerkte(df_resampling)

df_resampling_maerkte

In [ ]:
df_resampling_bestellungen = resampling_bestellungen(df_resampling)

df_resampling_bestellungen

In [10]:
df_corr_maerkte = korrelation_maerkte(df_maerkte, maerkte_neu, df_resampling_maerkte)

df_corr_maerkte

  dataset  mean_abs_delta  max_abs_delta
0   synth        0.022906       0.061070
1  resamp        0.089945       0.295094

In [11]:
df_corr_bestellungen = korrelation_bestellungen(df_bestellungen, bestellungen_neu, df_resampling_bestellungen)

df_corr_bestellungen

  dataset  mean_abs_delta  max_abs_delta
0   synth        0.010777       0.023134
1  resamp        0.004730       0.015674